### ISSUE TITLE
About - Sky`s Blog

### ISSUE THREAD

**Issue by wsk1103** [wsk1103/wsk1103.github.io#59]
https://wsk1103.github.io/about/ 

 那些我很冒险的梦

**Comment by B-White07** [comment]
你好，看了你的ssm二手平台的项目，导入到自己的idea中运行后，首页图片没办法正确显示，能请教一下应该怎么配置吗

**Comment by debug312** [comment]
您好，最近在参考您的基于springboot的微生活系统，出现了一些问题，请问能够请教下您嘛

**Comment by 896893492** [comment]
感谢你的C2C平台
